### ISSUE TITLE
Update parenface dependency

### ISSUE THREAD

**Issue by johnbendi** [skeeto/.emacs.d#8]
Parenface is now deprecated in favor of [paren-face](https://github.com/tarsius/paren-face). Please update!

**Comment by skeeto** [comment]
I'm currently using rainbow-delimiters, not parenface. You can see my 
list of packages here:

https://github.com/skeeto/.emacs.d/blob/master/packages.el

I have no reason to move away from rainbow-delimiters at this time.

**Comment by johnbendi** [comment]
Okay my bad. I was somehow still using your old revision. Closing as I have switched to latest. I am having some issues which I will report in another issue.
